# Banking Product!

This jupyter file will be used for the cleaning and structuring of the Bank's dataset.

### Imports

In [43]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

## Import the dataset

In [46]:
bankdata = pd.read_csv('Input/credit_test.csv',encoding = 'latin-1')
display(bankdata)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
#Let's check for the number of NaN for each column.
display(bankdata.isnull().sum())
#It look's like the last 353 rows are completely empty
display(bankdata.tail(354))

Loan ID                            0
Customer ID                        0
Current Loan Amount                0
Term                               0
Credit Score                    1981
Annual Income                   1981
Years in current job             427
Home Ownership                     0
Purpose                            0
Monthly Debt                       0
Years of Credit History            0
Months since last delinquent    5306
Number of Open Accounts            0
Number of Credit Problems          0
Current Credit Balance             0
Maximum Open Credit                0
Bankruptcies                      22
Tax Liens                          1
dtype: int64

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
9646,488b287b-6464-4f82-bd52-de92e93ba26a,06ffccfb-5875-4260-bda6-55de339cb5cf,515306.0,Long Term,673.0,2082324.0,8 years,Home Mortgage,Debt Consolidation,27590.66,11.9,71.0,20.0,1.0,194503.0,552024.0,1.0,0.0
9647,6d651640-89ef-4a71-bddb-b5c26737c2ae,83fcb29d-4c09-4913-b960-58cff246efc3,437844.0,Short Term,739.0,2646966.0,8 years,Home Mortgage,Debt Consolidation,20602.27,26.9,39.0,12.0,0.0,279167.0,457864.0,0.0,0.0
9648,6f327069-371b-4c52-a927-8df6a641df51,4ad84d3a-9921-4999-9151-1c44416351b3,99999999.0,Long Term,740.0,3390170.0,3 years,Home Mortgage,Debt Consolidation,27629.80,20.5,NaN,14.0,0.0,466203.0,1028192.0,0.0,0.0
9649,cc332aa6-151e-456e-a1b7-66d568d96f44,44f037ad-a6e2-400e-9d91-2cdba3354b46,662552.0,Short Term,708.0,2305574.0,1 year,Home Mortgage,Debt Consolidation,37465.72,10.9,80.0,12.0,0.0,381197.0,1076570.0,0.0,0.0
9650,a84bb63d-dedd-43be-b97f-f6d884ba3464,f96b7254-3872-4d26-b399-c383dd8edf0c,267608.0,Long Term,716.0,1155618.0,10+ years,Rent,Debt Consolidation,14252.66,14.1,NaN,13.0,1.0,332310.0,515108.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,c4ab66f9-833c-43b8-879c-4f8bcb64dd14,8ee2002b-8fb6-4af0-ab74-25a1c23e7647,157806.0,Short Term,731.0,1514376.0,6 years,Rent,Debt Consolidation,4795.41,12.5,NaN,9.0,0.0,87058.0,234410.0,0.0,0.0
9996,bbd3a392-01b4-4e0e-9c28-b2a4a39beac7,6c306306-f5c2-4db5-b74a-af2895123ecb,132550.0,Short Term,718.0,763192.0,4 years,Home Mortgage,Debt Consolidation,12401.87,9.9,20.0,8.0,0.0,74309.0,329692.0,0.0,0.0
9997,da9870de-4280-46a3-8fc6-91cfe5bfde9d,cc94e25e-1060-4465-b603-194e122f0239,223212.0,Long Term,NaN,NaN,NaN,Rent,Debt Consolidation,4354.42,27.2,NaN,8.0,1.0,99636.0,568370.0,1.0,0.0
9998,0cc8e0e0-1bc6-49d7-ad0f-0598b647458f,f90cf410-a34b-49e7-8af9-2b405e17b827,99999999.0,Short Term,721.0,972097.0,10+ years,Home Mortgage,Debt Consolidation,12232.20,16.8,24.0,8.0,1.0,184984.0,240658.0,0.0,0.0
9999,14f94b64-26c4-48fd-b916-1388d7adcc1d,f1838fa9-7ad9-44d5-97a6-7a6d3f3529d7,99999999.0,Short Term,748.0,1079960.0,6 years,Home Mortgage,Debt Consolidation,12239.61,19.7,NaN,14.0,0.0,179018.0,607882.0,0.0,0.0

In [50]:
#I am removing those 353 empty rows.
bankdata.drop(bankdata.tail(353).index,inplace=True) 
#I will not eliminate duplicate values for loan ID or Customer ID as I assume it is possible that a client 
#has two different loans or a loan has two different holders.