# Banking Product!

This jupyter file will be used for the cleaning and structuring of the Bank's dataset.

### Imports

In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import Cleaning_functions

## Import the dataset

In [2]:
bankdata = pd.read_csv('Input/credit_test.csv',encoding = 'latin-1')
display(bankdata)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#Let's check for the number of NaN for each column.
display(bankdata.isnull().sum())
#It look's like the last 353 rows are completely empty
display(bankdata.tail(353))

Loan ID                          353
Customer ID                      353
Current Loan Amount              353
Term                             353
Credit Score                    2334
Annual Income                   2334
Years in current job             780
Home Ownership                   353
Purpose                          353
Monthly Debt                     353
Years of Credit History          353
Months since last delinquent    5659
Number of Open Accounts          353
Number of Credit Problems        353
Current Credit Balance           353
Maximum Open Credit              353
Bankruptcies                     375
Tax Liens                        354
dtype: int64

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cleaning the data!

In [4]:
#I am removing those 353 empty rows.
bankdata.drop(bankdata.tail(353).index,inplace=True) 
#I will not eliminate duplicate values for loan ID or Customer ID as I assume it is possible that a client 
#has two different loans or a loan has two different holders.

In [5]:
#Now I am going to short the IDs for Loans and customers as they seem to be a pretty long string
bankdata['Loan ID'] = bankdata['Loan ID'].str[0:8] 
bankdata['Customer ID'] = bankdata['Customer ID'].str[0:8] 
bankdata.head(50)

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f,ded0b3c3,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947,1630e6e3,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01,2c60938b,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb,12116614,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f,39888105,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0
5,a4957169,6878d414,202928.0,Short Term,741.0,760380.0,1 year,Rent,Debt Consolidation,6526.69,13.8,NaN,6.0,0.0,258647.0,476872.0,0.0,0.0
6,43467302,48113a98,621786.0,Long Term,733.0,1783606.0,10+ years,Home Mortgage,Debt Consolidation,36563.98,15.3,NaN,42.0,0.0,281599.0,1449162.0,0.0,0.0
7,930c7cb3,19941661,266794.0,Long Term,NaN,NaN,< 1 year,Own Home,Debt Consolidation,12336.89,5.8,NaN,9.0,0.0,233206.0,342232.0,0.0,0.0
8,0b2f1b66,6a1adeda,202466.0,Short Term,736.0,1068617.0,5 years,Rent,Debt Consolidation,18745.21,20.5,NaN,2.0,0.0,0.0,0.0,0.0,0.0
9,d08f3a5e,4080a828,266288.0,Long Term,683.0,2031518.0,2 years,Rent,Debt Consolidation,12443.10,24.4,56.0,8.0,2.0,31445.0,251130.0,2.0,0.0
10,3102b699,8116b23d,121110.0,Short Term,NaN,NaN,< 1 year,Rent,Debt Consolidation,10749.44,19.2,52.0,4.0,0.0,102087.0,198330.0,0.0,0.0
11,663ad9a3,8ec9f388,258104.0,Short Term,723.0,1284514.0,7 years,Rent,Debt Consolidation,6368.99,14.6,64.0,12.0,0.0,128402.0,266904.0,0.0,0.0
12,1e277d73,db6fb330,161722.0,Short Term,680.0,504374.0,7 years,Rent,other,6094.63,9.5,NaN,13.0,0.0,167903.0,388828.0,0.0,0.0
13,79d992b7,3baae7fe,753016.0,Long Term,NaN,NaN,5 years,Home Mortgage,Debt Consolidation,9627.49,21.7,21.0,9.0,0.0,384522.0,657646.0,0.0,0.0
14,c3c63911,622add56,444664.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,22817.86,17.9,8.0,25.0,0.0,318953.0,971872.0,0.0,0.0
15,a913063f,4f8389cd,172282.0,Short Term,696.0,669560.0,3 years,Home Mortgage,Debt Consolidation,17966.78,18.2,NaN,16.0,0.0,431490.0,999262.0,0.0,0.0
16,e326b52a,8c49e3f3,275440.0,Short Term,729.0,1236976.0,6 years,Rent,Debt Consolidation,21647.08,35.8,NaN,13.0,0.0,151088.0,264242.0,0.0,0.0
17,add946a5,163b8125,218834.0,Short Term,742.0,1077262.0,3 years,Own Home,Home Improvements,19390.64,24.5,29.0,37.0,0.0,212800.0,502876.0,0.0,0.0
18,cb6f7b00,ce6fc244,99999999.0,Short Term,715.0,442339.0,< 1 year,Rent,Debt Consolidation,14007.18,17.0,25.0,14.0,0.0,65474.0,284966.0,0.0,0.0
19,e6246fe9,bcace9c1,99999999.0,Long Term,715.0,694526.0,8 years,Rent,Debt Consolidation,4358.22,17.3,47.0,5.0,0.0,137332.0,272734.0,0.0,0.0
20,ebefe6f6,bd73b695,346610.0,Short Term,744.0,2245116.0,2 years,Home Mortgage,Debt Consolidation,24134.94,17.6,68.0,14.0,0.0,729695.0,1307922.0,0.0,0.0
21,eda0e007,6518287d,99999999.0,Short Term,747.0,1394676.0,5 years,Home Mortgage,Other,5834.33,31.9,NaN,7.0,0.0,164350.0,569778.0,0.0,0.0
22,82bf9406,63e691e6,219648.0,Long Term,722.0,682898.0,10+ years,Home Mortgage,Debt Consolidation,18893.79,15.5,NaN,8.0,0.0,347396.0,553300.0,0.0,0.0
23,5dfdc862,61d66434,334620.0,Short Term,740.0,963300.0,10+ years,Home Mortgage,Debt Consolidation,16536.65,16.4,55.0,17.0,0.0,330581.0,843128.0,0.0,0.0
24,c5dca97f,85e3fb12,219868.0,Short Term,736.0,683582.0,6 years,Own Home,Debt Consolidation,9057.49,9.6,NaN,8.0,0.0,121467.0,215380.0,0.0,0.0
25,0905734d,c97bf871,222816.0,Long Term,708.0,990185.0,4 years,Home Mortgage,Debt Consolidation,6031.93,17.5,NaN,8.0,1.0,125020.0,343860.0,1.0,0.0
26,10d9c56c,aae249a1,108416.0,Short Term,NaN,NaN,10+ years,Rent,Debt Consolidation,41882.46,20.4,NaN,11.0,0.0,827051.0,1003816.0,0.0,0.0
27,ac8e5698,9a561b03,108152.0,Short Term,705.0,747156.0,4 years,Rent,Business Loan,20235.38,19.9,15.0,14.0,0.0,174344.0,348062.0,0.0,0.0
28,a656f70b,3b69f3b7,174724.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,11341.29,8.2,NaN,4.0,0.0,85633.0,126632.0,0.0,0.0
29,6b3d25b3,3d5b68c4,404008.0,Long Term,NaN,NaN,6 years,Home Mortgage,Debt Consolidation,42159.86,15.9,NaN,16.0,0.0,684950.0,1054636.0,0.0,0.0
30,af0a5a13,322fdfe1,360228.0,Short Term,740.0,2138906.0,10+ years,Home Mortgage,Debt Consolidation,27984.15,15.5,18.0,8.0,0.0,164008.0,225280.0,0.0,0.0
31,d4407af5,7883d485,218724.0,Short Term,NaN,NaN,< 1 year,HaveMortgage,Take a Trip,4967.36,11.0,6.0,7.0,0.0,16511.0,108064.0,0.0,0.0
32,65d23a2f,6866ead5,441012.0,Short Term,738.0,979716.0,10+ years,Rent,Debt Consolidation,12899.67,27.3,NaN,11.0,0.0,380228.0,608938.0,0.0,0.0
33,f95c766b,481df4a0,337370.0,Long Term,717.0,1146004.0,1 year,Rent,Debt Consolidation,14802.33,21.0,32.0,9.0,0.0,256139.0,423104.0,0.0,0.0
34,cc43b784,54459ce0,765688.0,Long Term,706.0,5951484.0,3 years,Rent,small_business,61498.63,22.4,NaN,13.0,0.0,549100.0,1464980.0,0.0,0.0
35,f8fa11bd,ab86ebb2,468908.0,Long Term,6470.0,1833842.0,8 years,Rent,other,5898.93,14.4,NaN,19.0,1.0,183863.0,809490.0,1.0,0.0
36,875c3df0,1b233b3a,219428.0,Short Term,712.0,1301671.0,NaN,Rent,Debt Consolidation,22237.03,15.6,NaN,9.0,0.0,458679.0,624096.0,0.0,0.0
37,769e4e52,401b284d,574904.0,Short Term,706.0,1306592.0,9 years,Rent,other,8078.99,14.0,NaN,4.0,0.0,1596.0,306196.0,0.0,0.0
38,41e8f5a6,3c6cdac9,401192.0,Short Term,704.0,1539912.0,10+ years,Rent,Debt Consolidation,27500.41,22.0,NaN,18.0,0.0,423092.0,769054.0,0.0,0.0
39,c3552bfe,b171374b,257444.0,Short Term,736.0,648508.0,10+ years,Rent,Debt Consolidation,5944.53,17.5,46.0,10.0,0.0,204516.0,621566.0,0.0,0.0
40,89dbf9cb,16f4e4a9,309694.0,Long Term,NaN,NaN,10+ years,Own Home,Debt Consolidation,23473.17,26.0,38.0,10.0,0.0,402059.0,650188.0,0.0,0.0
41,dd80a04f,55cedc7a,214258.0,Short Term,NaN,NaN,1 year,Rent,Debt Consolidation,7207.46,12.8,69.0,10.0,1.0,209361.0,338580.0,0.0,0.0
42,4066eff2,23bb03ea,325754.0,Short Term,NaN,NaN,4 years,Home Mortgage,Debt Consolidation,14301.30,25.0,13.0,11.0,0.0,165186.0,466532.0,0.0,0.0
43,a652d67e,4aec62aa,651354.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Home Improvements,32314.25,19.1,37.0,21.0,0.0,356687.0,1868768.0,0.0,0.0
44,628dd91e,cef6a8aa,262108.0,Short Term,733.0,855342.0,7 years,Rent,Debt Consolidation,9194.86,22.8,NaN,5.0,0.0,110884.0,224840.0,0.0,0.0
45,1e5e3699,67a35b69,310376.0,Short Term,NaN,NaN,2 years,Rent,Debt Consolidation,5101.12,8.5,NaN,10.0,0.0,126179.0,241890.0,0.0,0.0
46,b69432ba,75a48dbf,429616.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,21998.58,22.3,25.0,12.0,0.0,321898.0,847066.0,0.0,0.0
47,2f5d0697,6bdae209,414744.0,Short Term,706.0,1164225.0,10+ years,Rent,Debt Consolidation,14746.66,10.5,NaN,17.0,0.0,258172.0,797170.0,0.0,0.0
48,8ab9234f,5ef6d424,654126.0,Long Term,646.0,2504504.0,9 years,Home Mortgage,other,14818.48,31.9,11.0,7.0,0.0,130264.0,187594.0,0.0,0.0
49,42a25517,395a76dd,539990.0,Long Term,682.0,1790807.0,2 years,Home Mortgage,Debt Consolidation,24026.64,17.3,53.0,13.0,1.0,81358.0,382910.0,1.0,0.0

In [6]:
bankdata = bankdata.fillna(0)
display(bankdata.isnull().sum())

Loan ID                         0
Customer ID                     0
Current Loan Amount             0
Term                            0
Credit Score                    0
Annual Income                   0
Years in current job            0
Home Ownership                  0
Purpose                         0
Monthly Debt                    0
Years of Credit History         0
Months since last delinquent    0
Number of Open Accounts         0
Number of Credit Problems       0
Current Credit Balance          0
Maximum Open Credit             0
Bankruptcies                    0
Tax Liens                       0
dtype: int64

In [7]:
bankdata['Years in current job'].value_counts()

10+ years    3085
2 years       916
3 years       866
< 1 year      795
5 years       696
1 year        648
4 years       613
6 years       566
7 years       554
8 years       472
0             427
9 years       362
Name: Years in current job, dtype: int64

In [8]:
from Cleaning_functions import roundamount
from Cleaning_functions import roundamountmonth
from Cleaning_functions import roundscore

In [9]:
bankdata['Current Loan Amount'] = bankdata['Current Loan Amount'].apply(roundamount())
bankdata['Monthly Debt'] = bankdata['Monthly Debt'].apply(roundamountmonth())
bankdata['Current Credit Balance'] = bankdata['Current Credit Balance'].apply(roundamount())
bankdata['Maximum Open Credit'] = bankdata['Maximum Open Credit'].apply(roundamount())
bankdata['Annual Income'] = bankdata['Annual Income'].apply(roundamount())
bankdata['Credit Score'] = bankdata['Credit Score'].apply(roundscore())
bankdata.rename(columns={'Current Loan Amount': 'Current Loan Amount($)', 'Monthly Debt': 'Monthly Debt($)', 'Current Credit Balance': 'Current Credit Balance($)', 'Maximum Open Credit': 'Maximum Open Credit($)', 'Annual Income': 'Annual Income($)'}, inplace=True)

In [10]:
bankdata

,Loan ID,Customer ID,Current Loan Amount($),Term,Credit Score,Annual Income($),Years in current job,Home Ownership,Purpose,Monthly Debt($),Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance($),Maximum Open Credit($),Bankruptcies,Tax Liens
0,f738779f,ded0b3c3,60000.0,Short Term,7.47,210000.0,10+ years,Home Mortgage,Debt Consolidation,4200.0,21.8,0.0,9.0,0.0,60000.0,110000.0,0.0,0.0
1,6dcc0947,1630e6e3,30000.0,Short Term,7.34,190000.0,10+ years,Home Mortgage,Debt Consolidation,3700.0,19.4,0.0,11.0,0.0,70000.0,90000.0,0.0,0.0
2,f7744d01,2c60938b,20000.0,Short Term,7.09,90000.0,2 years,Rent,Debt Consolidation,800.0,12.5,10.0,10.0,0.0,0.0,40000.0,0.0,0.0
3,83721ffb,12116614,20000.0,Short Term,7.27,80000.0,10+ years,Rent,Debt Consolidation,1700.0,16.5,27.0,16.0,1.0,20000.0,50000.0,1.0,0.0
4,08f3789f,39888105,30000.0,Short Term,7.44,180000.0,10+ years,Home Mortgage,Debt Consolidation,3900.0,26.0,44.0,14.0,0.0,40000.0,50000.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,c4ab66f9,8ee2002b,20000.0,Short Term,7.31,150000.0,6 years,Rent,Debt Consolidation,500.0,12.5,0.0,9.0,0.0,10000.0,20000.0,0.0,0.0
9996,bbd3a392,6c306306,10000.0,Short Term,7.18,80000.0,4 years,Home Mortgage,Debt Consolidation,1200.0,9.9,20.0,8.0,0.0,10000.0,30000.0,0.0,0.0
9997,da9870de,cc94e25e,20000.0,Long Term,0.00,0.0,0,Rent,Debt Consolidation,400.0,27.2,0.0,8.0,1.0,10000.0,60000.0,1.0,0.0
9998,0cc8e0e0,f90cf410,10000000.0,Short Term,7.21,100000.0,10+ years,Home Mortgage,Debt Consolidation,1200.0,16.8,24.0,8.0,1.0,20000.0,20000.0,0.0,0.0
9999,14f94b64,f1838fa9,10000000.0,Short Term,7.48,110000.0,6 years,Home Mortgage,Debt Consolidation,1200.0,19.7,0.0,14.0,0.0,20000.0,60000.0,0.0,0.0

In [11]:
bankdata = bankdata.drop(columns = ['Number of Open Accounts','Number of Credit Problems','Tax Liens'])

In [12]:
bankdata.drop(bankdata.loc[bankdata['Current Loan Amount($)']==10000000.0].index, inplace=True)
bankdata.drop(bankdata.loc[bankdata['Annual Income($)']==0.0].index, inplace=True)
bankdata.reset_index(drop=True)

,Loan ID,Customer ID,Current Loan Amount($),Term,Credit Score,Annual Income($),Years in current job,Home Ownership,Purpose,Monthly Debt($),Years of Credit History,Months since last delinquent,Current Credit Balance($),Maximum Open Credit($),Bankruptcies
0,f738779f,ded0b3c3,60000.0,Short Term,7.47,210000.0,10+ years,Home Mortgage,Debt Consolidation,4200.0,21.8,0.0,60000.0,110000.0,0.0
1,6dcc0947,1630e6e3,30000.0,Short Term,7.34,190000.0,10+ years,Home Mortgage,Debt Consolidation,3700.0,19.4,0.0,70000.0,90000.0,0.0
2,f7744d01,2c60938b,20000.0,Short Term,7.09,90000.0,2 years,Rent,Debt Consolidation,800.0,12.5,10.0,0.0,40000.0,0.0
3,83721ffb,12116614,20000.0,Short Term,7.27,80000.0,10+ years,Rent,Debt Consolidation,1700.0,16.5,27.0,20000.0,50000.0,1.0
4,08f3789f,39888105,30000.0,Short Term,7.44,180000.0,10+ years,Home Mortgage,Debt Consolidation,3900.0,26.0,44.0,40000.0,50000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6881,4d0d0e65,add5361a,40000.0,Long Term,6.97,220000.0,6 years,Home Mortgage,Debt Consolidation,1700.0,22.1,0.0,40000.0,50000.0,0.0
6882,6f0b1e02,879d5bf4,20000.0,Short Term,7.37,120000.0,< 1 year,Rent,Debt Consolidation,2000.0,9.5,0.0,30000.0,40000.0,0.0
6883,a2701102,6dc5fa63,40000.0,Short Term,7.39,150000.0,7 years,Home Mortgage,Debt Consolidation,1900.0,16.7,79.0,40000.0,70000.0,0.0
6884,c4ab66f9,8ee2002b,20000.0,Short Term,7.31,150000.0,6 years,Rent,Debt Consolidation,500.0,12.5,0.0,10000.0,20000.0,0.0
6885,bbd3a392,6c306306,10000.0,Short Term,7.18,80000.0,4 years,Home Mortgage,Debt Consolidation,1200.0,9.9,20.0,10000.0,30000.0,0.0

In [13]:
bankdata['Home Ownership']= bankdata['Home Ownership'].str.replace(r'(.*)?(Mortgage)(.*)', 'Mortgage')
bankdata['Purpose']= bankdata['Purpose'].str.replace(r'(.*)?(other)(.*)', 'Other')

In [14]:
bankdata['Annual Income($)'].value_counts()

100000.0    571
90000.0     569
80000.0     500
110000.0    475
120000.0    457
           ...
810000.0      1
800000.0      1
720000.0      1
650000.0      1
630000.0      1
Name: Annual Income($), Length: 78, dtype: int64

In [15]:
bankdata['Home Ownership'].value_counts()

Mortgage    3299
Rent        2943
Own Home     644
Name: Home Ownership, dtype: int64

In [16]:
bankdata['Purpose'].value_counts()

Debt Consolidation      5399
Other                    617
Home Improvements        409
Business Loan            117
Medical Bills             89
Buy a Car                 88
Buy House                 51
major_purchase            36
Take a Trip               28
small_business            22
Educational Expenses      12
moving                     8
wedding                    6
vacation                   3
renewable_energy           1
Name: Purpose, dtype: int64

In [17]:
bankdata['Term'].value_counts()

Short Term    4882
Long Term     2004
Name: Term, dtype: int64